### ISSUE TITLE
SYMFONY5 SUPPORT FOR SYMFONY/PROCESS

### ISSUE THREAD

**Issue by fcerezo** [backup-manager/symfony#65]
Hi

When I tried to update to 2.3.* I got this error

 Problem 1
    - backup-manager/backup-manager 1.4.1 requires symfony/process ^2.1 || ^3.0 || ^4 -> no matching package found.
    - backup-manager/backup-manager 1.4 requires symfony/process ^2.1 || ^3.0 || ^4.0 -> no matching package found.
    - backup-manager/backup-manager 1.3.0 requires symfony/process ^2.1 || ^3.0 || ^4.0 -> no matching package found.
    - backup-manager/symfony 2.3.0 requires backup-manager/backup-manager ^1.3 -> satisfiable by backup-manager/backup-manager[1.3.0, 1.4, 1.4.1].
    - Installation request for backup-manager/symfony 2.3.* -> satisfiable by backup-manager/symfony[2.3.0].

But I have the symfony/process in 5.0.3 version. Any idea?

**Comment by fcerezo** [comment]
Hi all is there anyone ? Thanks

**Comment by ShawnMcCool** [comment]
yeah so the version 1.4 matches on 4.0 as the highest.

i recommend either switching to backup manager 2.x

or forking 1.4.1 and upgrading the dependency here

https://github.com/backup-manager/backup-manager/blob/1.4.1/composer.json

then test it to make sure it works, then submit a pull request.

**Comment by fcerezo** [comment]
Sorry. But I dont know how to do it. Could you help me?

**Comment by ShawnMcCool** [comment]
First: I recommend just upgrading backup manager to 2.0 by changing the version in your composer.json to:  "^2"

Try running it, see if there's errors, etc.

If you don't want to do this for some reason (It is really a good solution here) then let me know.

**Comment by fcerezo** [comment]
I added this line

"backup-manager/backup-manager": "^2.1"

And it was installed OK. But when I tried to install 

composer require backup-manager/symfony  

I get this error 

Using version ^2.3 for backup-manager/symfony
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for backup-manager/symfony ^2.3 -> satisfiable by backup-manager/symfony[2.3.0].
    - backup-manager/symfony 2.3.0 requires backup-manager/backup-manager ^1.3 -> satisfiable by backup-manager/backup-manager[1.3.0, 1.4, 1.4.1] but these conflict with your requirements or minimum-stability.

Any idea?

**Comment by ShawnMcCool** [comment]
Yeah OK so it looks like the Symfony driver needs to be upgraded to support the new backup manager release.

@Nyholm Do you know anything about how to go about this? I can't imagine there's much to change.

**Comment by Nyholm** [comment]
I dont believe it is. It might be as easy as just updating composer.json to support both version 1 and 2.

**Comment by fcerezo** [comment]
Can you update it ? Thanks

**Comment by fcerezo** [comment]
Any news for that?

**Comment by ShawnMcCool** [comment]
I personally don't have time to pursue this at the moment. @Nyholm not sure if you do.

@fcerezo might be worth just forking it and trying it out.

**Comment by Nyholm** [comment]
@fcerezo It is an open source library. The greatness is in the collective. 

Please update it it yourself. Test it and make a PR. I would be happy to merge that PR and tag a release for you. 

Im sure that I don't have to remind anybody that open source maintainers are not the company's IT department.

**Comment by fcerezo** [comment]
Yes, I know. I have been trying it but I dont know how to fix it. I have no too much experience with forks and pull requests.

**Comment by ShawnMcCool** [comment]
Hey no problem at all. Try forking the repository by going to its main page and clicking 'fork' near the top. Fork it to your account, then clone your forked version locally. Create a new branch in it called something like.. "upgrade-symfony" 

git checkout -B upgrade-symfony-driver master

Now, modify that repository the way that you want (modify composer.json). Update composer "composer update".

Once you have it all the way that you want it, you can push this branch to github.

git push -u origin upgrade-symfony-driver

Now you'll find the branch on your github repository page.

Then you can, instead of installing backup-manager/symfony.. Install your fork's branch.

More details by the fantastic Lorna Jane here https://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency

If you install your fork successfully, it'll pull in the correct version of the backup manager, then you can see if it works.

Let me know if you run into any unexpected problems.
